version: '3.7'
services:
  spellcheck-application:
    build: .
    image: assignment4:latest
    ports:
      - "8080:5000"
    environment:
      DB_ADMIN_USER: admin
      DB_ADMIN_PWORD: /run/secrets/db_admin_pword
      DB_ADMIN_2FA: /run/secrets/db_admin_2fa
      CSRF_KEY: /run/secrets/csrf_key
    secrets:
      - db_admin_pword
      - db_admin_2fa
      - csrf_key
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

secrets:
  db_admin_pword:
    external: true
    #file: ./db_admin_pword.txt
  db_admin_2fa:
    external: true
    #file: ./db_admin_2fa.txt
  csrf_key:
    external: true
    #file: ./csrf_key.txt